# Generated by Django 4.0.5 on 2022-06-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='rtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
