# Generated by Django 4.0.5 on 2022-06-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_detail_rtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='images')),
                ('desc', models.TextField(max_length=500)),
                ('upload_by', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
