# Generated by Django 4.0.5 on 2022-06-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
